# Generated by Django 5.0.8 on 2024-08-18 19:16

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('lessons', '0001_initial'), ('lessons', '0002_lesson_language'), ('lessons', '0003_keyconcept_image'), ('lessons', '0004_transcript_transcriptmessage'), ('lessons', '0005_remove_transcriptmessage_transcript_and_more'), ('lessons', '0006_alter_lesson_table')]

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Provide a brief introduction to the lesson. This will be shown to the student before they start the interactive dialogue.')),
                ('location', models.CharField(help_text="Specify the location or setting for this lesson (e.g., 'Coffee Shop', 'Airport', 'Art Gallery'). This will be used to set the context for the AI dialogue.", max_length=100)),
                ('difficulty_level', models.CharField(choices=[('a1', 'A1 - Beginner'), ('a2', 'A2 - Elementary'), ('b1', 'B1 - Intermediate'), ('b2', 'B2 - Upper Intermediate'), ('c1', 'C1 - Advanced'), ('c2', 'C2 - Proficiency')], default='a1', help_text="Select the CEFR level for this lesson. This will help tailor the AI's language complexity to the student's proficiency.", max_length=20)),
                ('estimated_time', models.PositiveIntegerField(default=30, help_text='Estimate the time (in minutes) it will take to complete this lesson, including the interactive dialogue.')),
                ('llm_system_prompt', models.TextField(help_text="Provide specific instructions for the AI assistant's behavior in this lesson. For example, 'You are a friendly barista in a busy coffee shop. Engage the student in small talk and help them order a drink.'", verbose_name='LLM System Prompt')),
                ('cover_photo', models.ForeignKey(blank=True, help_text='Choose an image that represents the setting or theme of the lesson. This will help set the scene for the student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('language', models.CharField(default='English', help_text="Specify the target language for this lesson (e.g., 'English', 'Spanish', 'French'). This will help the AI assistant provide appropriate responses and suggestions.", max_length=100)),
            ],
            options={
                'verbose_name': 'Language Lesson',
                'verbose_name_plural': 'Language Lessons',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='KeyConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(help_text='Enter a key language concept or vocabulary item for this lesson.', max_length=255)),
                ('lesson', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_concepts', to='lessons.lesson')),
                ('image', models.ForeignKey(blank=True, help_text='Choose an image that represents the key concept. This will help the student visualize the concept.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
        ),
        migrations.AlterModelTable(
            name='lesson',
            table='lessons',
        ),
    ]
