# Generated by Django 5.0.8 on 2024-08-12 15:56

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_rename_lessonpage_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="difficulty_level",
            field=models.CharField(
                choices=[
                    ("a1", "A1 - Beginner"),
                    ("a2", "A2 - Elementary"),
                    ("b1", "B1 - Intermediate"),
                    ("b2", "B2 - Upper Intermediate"),
                    ("c1", "C1 - Advanced"),
                    ("c2", "C2 - Proficiency"),
                ],
                default="a1",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="estimated_time",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Estimated time to complete the lesson (in minutes)",
            ),
        ),
        migrations.CreateModel(
            name="KeyConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concept", models.CharField(max_length=255)),
                (
                    "lesson",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_concepts",
                        to="lessons.lesson",
                    ),
                ),
            ],
        ),
    ]
