# Generated by Django 5.0.8 on 2024-08-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0003_lesson_difficulty_level_lesson_estimated_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="llm_system_prompt",
            field=models.TextField(
                blank=True,
                help_text="Provide the system prompt for the LLM agent to define its role and behavior.",
                verbose_name="LLM System Prompt",
            ),
        ),
    ]
