# Generated by Django 5.0.8 on 2024-08-18 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_remove_transcriptmessage_transcript_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lesson',
            table='lessons',
        ),
    ]
