# Generated by Django 5.0.8 on 2024-09-03 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0008_lesson_voice_alter_lesson_language"),
        ("transcripts", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Lesson",
            new_name="ChatLesson",
        ),
    ]
