# Generated by Django 5.0.8 on 2024-09-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0011_alter_chatlesson_minigames"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="keyconcept",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="keyconcept",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
