# Generated by Django 5.0.8 on 2024-09-06 15:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0012_alter_keyconcept_options_keyconcept_sort_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatlesson",
            name="minigames",
            field=wagtail.fields.StreamField(
                [("step_order_game", 7), ("iframe", 13)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title of the sequence", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Description of the sequencing task",
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Main image for the sequencing task",
                            "required": True,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Name of the step", "required": True},
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Image for the step", "required": True},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 3), ("image", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.ListBlock", (5,), {}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("description", 1),
                                ("main_image", 2),
                                ("steps", 6),
                            ]
                        ],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "URL for the iframe src", "required": True},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Query parameter key", "required": True},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Query parameter value", "required": True},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("key", 9), ("value", 10)]],
                        {"required": False},
                    ),
                    12: (
                        "wagtail.blocks.ListBlock",
                        (11,),
                        {"help_text": "Optional query parameters"},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 8), ("query_params", 12)]],
                        {},
                    ),
                },
            ),
        ),
    ]
