# Generated by Django 5.1.7 on 2025-03-10 17:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0015_alter_chatlesson_minigames"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatlesson",
            name="minigames",
            field=wagtail.fields.StreamField(
                [("step_order_game", 8), ("iframe", 14)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Title of the minigame", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Description of the minigame", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Instructions for the minigame",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Main image for the sequencing task",
                            "required": True,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Name of the step", "required": True},
                    ),
                    5: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Image for the step", "required": True},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 4), ("image", 5)]],
                        {},
                    ),
                    7: ("wagtail.blocks.ListBlock", (6,), {}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("description", 1),
                                ("instructions", 2),
                                ("main_image", 3),
                                ("steps", 7),
                            ]
                        ],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "URL for the iframe src", "required": True},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Query parameter key", "required": True},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Query parameter value", "required": True},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("key", 10), ("value", 11)]],
                        {"required": False},
                    ),
                    13: (
                        "wagtail.blocks.ListBlock",
                        (12,),
                        {
                            "default": [],
                            "help_text": "Optional query parameters",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("description", 1),
                                ("instructions", 2),
                                ("url", 9),
                                ("query_params", 13),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
