from .choices import CEFRLevel

CEFR_LEVEL_INSTRUCTIONS = {
    CEFRLevel.A1: "Use very simple and short sentences, focusing on basic vocabulary and common expressions. Repeat key phrases frequently and use lots of visual cues or context clues. Speak slowly and clearly, using only the most basic grammar structures. Introduce new vocabulary gradually, always in clear contexts. Be very patient and encouraging, providing ample opportunities for the learner to practice simple greetings, introductions, and basic personal information exchanges.",
    CEFRLevel.A2: "Use simple sentences and basic vocabulary, but introduce some variety in sentence structure. Include common everyday expressions and very basic phrases related to areas of immediate relevance (e.g., personal information, shopping, local geography, employment). Speak clearly and somewhat slowly. Introduce new vocabulary related to familiar topics. Encourage learners to engage in simple, direct exchanges of information on familiar and routine matters.",
    CEFRLevel.B1: "Use clear, standard language on familiar matters. Introduce more complex sentence structures and a wider range of vocabulary, but still focus on common, everyday language. Speak at a moderate pace. Include idiomatic expressions sparingly, always with context. Encourage learners to describe experiences, events, dreams, hopes, and ambitions, and briefly give reasons and explanations for opinions and plans. Engage in conversations on topics related to work, school, and leisure time.",
    CEFRLevel.B2: "Use more complex language structures and a broad vocabulary range. Introduce abstract and concrete topics, including technical discussions in the learner's field of specialization. Speak at a natural pace. Use idiomatic expressions more frequently. Encourage learners to interact with a degree of fluency and spontaneity that makes regular interaction with native speakers possible without strain for either party. Prompt them to produce clear, detailed text on a wide range of subjects and explain viewpoints on topical issues.",
    CEFRLevel.C1: "Use sophisticated language structures and a wide range of vocabulary, including idiomatic expressions and colloquialisms. Speak at a natural pace, using stress and intonation to convey finer shades of meaning. Introduce complex and abstract topics, encouraging learners to understand and use language flexibly and effectively for social, academic, and professional purposes. Challenge them to produce clear, well-structured, detailed responses on complex subjects, showing controlled use of organizational patterns, connectors, and cohesive devices.",
    CEFRLevel.C2: "Use highly sophisticated language structures and an extensive vocabulary range, including nuanced and precise terms. Speak naturally, with no simplification. Introduce any topic, no matter how abstract or complex. Use humor, irony, and implicit meanings. Encourage learners to understand with ease virtually everything heard or read, to summarize information from different spoken and written sources, and to reconstruct arguments and accounts in a coherent presentation. Challenge them to express themselves spontaneously, very fluently, and precisely, differentiating finer shades of meaning even in more complex situations.",
}


def get_cefr_level_instructions(difficulty_level):
    return CEFR_LEVEL_INSTRUCTIONS.get(difficulty_level, "")
